name: Build

on:
  workflow_call:
    inputs:
      ref:
        description: Git ref (commit, branch, or tag) to build
        required: true
        type: string
      pkg_version:
        description: Explicit package version without a leading v
        required: false
        type: string
    outputs:
      pkg_version:
        description: Build version
        value: ${{ jobs.version.outputs.pkg_version }}

jobs:
  version:
    name: Determine package version
    runs-on: ubuntu-latest
    outputs:
      pkg_version: ${{ steps.version.outputs.pkg_version }}
    steps:
    - name: Clone tree
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
      with:
        fetch-depth: 0
        ref: ${{ inputs.ref }}
    - name: Determine release version
      id: version
      env:
        PACKAGE_VERSION: ${{ inputs.pkg_version }}
      run: |
        if [ -n "$PACKAGE_VERSION" ]; then
          echo "pkg_version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
        elif TAG=$(git describe --tags --match 'v*' 2>/dev/null); then
          echo "pkg_version=${TAG#v}" >> $GITHUB_OUTPUT
        else
          SHORT_HASH=$(git rev-parse --short HEAD)
          echo "pkg_version=0.0.0-0-unofficial-${SHORT_HASH}" >> $GITHUB_OUTPUT
        fi

  msvc:
    name: MSVC Profile
    needs: version
    uses: ./.github/workflows/windows-msvc.yml
    with:
      ref: ${{ inputs.ref }}
      pkg_version: ${{ needs.version.outputs.pkg_version }}
